### ISSUE TITLE
URL for endpoint

### ISSUE THREAD

**Issue by peteowlett** [staffomatic/staffomatic-api-documentation#1]
I had difficulty interpreting the initial connection instructions - where it said:

```
All URLs start with https://api.easypepapp.com/v3/demo or https://api.staffomaticapp.com/v3/demo. 
```

I didn't realise I needed to change `demo` to the name of our app. Maybe change it to something like:

```
All URLs start with https://api.easypepapp.com/v3/<your-app-name> or https://api.staffomaticapp.com/v3/<your-app-name>. 
```

**Comment by fluxsaas** [comment]
yeah, right. i have updated the readme. thanks!
