### ISSUE TITLE
422 on Application

### ISSUE THREAD

**Issue by 147896325** [staffomatic/staffomatic-api-documentation#2]
Hi,

I get a 422 error when i'm trying to assign/apply an user to an application, with an error like : "user already exists".
How can I make it works ?
The documentation doesn't tell so much about errors.

**Comment by harryjmg** [comment]
This error simply means you already assigned/applied to the shift.
Try to make an assign/apply request with an other shift, it should work.

**Comment by fluxsaas** [comment]
yes, correct, let me know if you need further help.
