### ISSUE TITLE
Schedules endpoint returning non existing schedules with location_id of deleted locations

### ISSUE THREAD

**Issue by mbriels** [staffomatic/staffomatic-api-documentation#6]
I use the **location** endpoint to get a list of all current locations in my account. Next to that I use the **schedules** endpoint to get schedules starting between a timewindow (4 weeks in the past, 4 weeks to the future).

I noticed that in the list of schedules, there are schedules with `location_id` for locations that were deleted a long time ago. 

Is this a bug? Could you explain why this happens?

**Comment by fluxsaas** [comment]
hey @mbriels 

please get in contact with our support directly so we can have a look into your account and solve that problem. Log into your account and use the chat window or get in contact here:

https://staffomatic.com/en/contact

best,
Kalle
